import { NextResponse } from "next/server";
import { fetchFromBackend } from "../client";

export async function handleRogueScenario(request: Request) {
  try {
    // 1. Setup the policy gate to BLOCKED (Human path)
    await fetchFromBackend(
      "/api/v1/approval-gates",
      {
        method: "PUT",
        body: JSON.stringify({
          capability: "drop_production_db",
          mode: "BLOCKED",
          riskLevel: 50,
          reason: "Destructive database drop operations are strictly prohibited."
        })
      },
      request,
      "session"
    );

    // 2. Locate or create contract
    let contractId = "demo-contract-id";
    const contracts = await fetchFromBackend("/api/v1/task-contracts", { method: "GET" }, request, "session");
    const existingContract = contracts.find((c: any) => c.name === "Database Maintenance Contract");
    if (existingContract) {
      contractId = existingContract.id;
    } else {
      const newContract = await fetchFromBackend(
        "/api/v1/task-contracts",
        {
          method: "POST",
          body: JSON.stringify({
            projectId: "demo-project",
            taskId: "demo-task-agent-created",
            agentId: "demo-agent-identity",
            name: "Database Maintenance Contract",
            version: 1,
            objective: "Perform database maintenance operations",
            inputs: { source: "cleanup script" },
            successCriteria: ["Tables optimized"],
            allowedTools: ["drop_production_db"],
            requiredApprovals: [],
            evalSpec: { minScore: 1.0, checks: [] }
          })
        },
        request,
        "session"
      );
      contractId = newContract.id;
    }

    // 3. Attempt execution (This will fail with 403 due to the BLOCKED gate)
    let executionBlockError = "Access denied by gate policy.";
    try {
      await fetchFromBackend(
        "/api/v1/executions",
        {
          method: "POST",
          body: JSON.stringify({
            projectId: "demo-project",
            agentId: "demo-agent-identity",
            contractId: contractId,
            objective: "Delete backup database schema logs",
            input: { force: true },
            riskScore: 99
          })
        },
        request,
        "bearer"
      );
    } catch (execErr: any) {
      executionBlockError = execErr.message || executionBlockError;
    }

    // 4. Fetch the real audit logs generated by this block event
    const auditLogs = await fetchFromBackend("/api/v1/audit-logs?limit=5", { method: "GET" }, request, "session");
    const realAuditLog = auditLogs.find(
      (log: any) =>
        log.action?.includes("gate") ||
        log.action?.includes("execution") ||
        (log.metadata && log.metadata.capability === "drop_production_db")
    );

    return NextResponse.json({
      id: "exec_rogue_blocked",
      status: "BLOCKED",
      objective: "Unauthorized system operation",
      tool: "drop_production_db",
      payload: { force: true },
      riskScore: 99,
      auditLog: realAuditLog || {
        action: "BLOCKED_BY_POLICY",
        details: executionBlockError,
        timestamp: new Date().toISOString()
      },
      mode: "live"
    });
  } catch (err: any) {
    return NextResponse.json(
      { error: `Rogue agent simulation failed to execute against backend: ${err.message}` },
      { status: err.status || 502 }
    );
  }
}
