export const errorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_SCOPE: "INSUFFICIENT_SCOPE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof errorCodes;
